#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Command {
    PlayPause,
    Stop,
    Seek { seconds: f64 },
    SetSpeed { speed: f64 },
    AdjustSpeed { delta: f64 },
    SetVolume { percent: f64 },
    AdjustVolume { delta: f64 },
    ToggleMute,
    FrameStep { forward: bool },
    KeyframeStep { forward: bool },
    ChapterStep { forward: bool },
    SubtitleDelay { delta_ms: i64 },
    SubtitleFontSize { delta: f32 },
    SubtitlePosition { delta_y: f32 },
    SubtitleToggle,
    SubtitleCycleTrack,
    AudioCycleTrack,
    SetAspectRatio { ratio: String },
    TransformZoom { delta: f64 },
    TransformPan { dx: f64, dy: f64 },
    TransformRotate { degrees: i32 },
    TransformFlipH,
    TransformFlipV,
    TransformReset,
    ToggleFullscreen,
    TogglePip,
    ToggleDiagnostics,
    TogglePlaylist,
    ToggleControlPanel,
    TogglePreferences,
    ToggleBookmarkStudio,
    ToggleSubtitleExplorer,
    ToggleSettingsInspector,
    ToggleFileNavigator,
    ToggleMediaInfo,
    ApplyProfile { name: String },
    TakeScreenshot,
}
